import type { Metadata } from "next";

import "@tailwind/styles";
import { AppWrapper, Toaster } from "@web-shared/components";
import { Cairo } from "next/font/google";

import "./global.css";

const сairo = Cairo({
  subsets: ["latin"],
  weight: ["200", "400", "500", "700"],
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={сairo.className}>
        {/* <div className="flex h-screen bg-green-800 w-full flex-col">{children}</div> */}
        <AppWrapper>{children}</AppWrapper>
        <Toaster />
      </body>
    </html>
  );
}
